p8105_hw2_zl3263
================
2022-10-03

#### package import

``` r
library(tidyverse)
```

    ## ── Attaching packages ─────────────────────────────────────── tidyverse 1.3.2 ──
    ## ✔ ggplot2 3.3.6      ✔ purrr   0.3.4 
    ## ✔ tibble  3.1.8      ✔ dplyr   1.0.10
    ## ✔ tidyr   1.2.0      ✔ stringr 1.4.1 
    ## ✔ readr   2.1.2      ✔ forcats 0.5.2 
    ## ── Conflicts ────────────────────────────────────────── tidyverse_conflicts() ──
    ## ✖ dplyr::filter() masks stats::filter()
    ## ✖ dplyr::lag()    masks stats::lag()

``` r
library(readxl)
```

### Problem 1

``` r
NYC_subway = read_csv("Datasets/NYC_Transit_Subway_Entrance_And_Exit_Data.csv") %>%
  janitor::clean_names()
```

    ## Rows: 1868 Columns: 32
    ## ── Column specification ────────────────────────────────────────────────────────
    ## Delimiter: ","
    ## chr (22): Division, Line, Station Name, Route1, Route2, Route3, Route4, Rout...
    ## dbl  (8): Station Latitude, Station Longitude, Route8, Route9, Route10, Rout...
    ## lgl  (2): ADA, Free Crossover
    ## 
    ## ℹ Use `spec()` to retrieve the full column specification for this data.
    ## ℹ Specify the column types or set `show_col_types = FALSE` to quiet this message.

``` r
NYC_subway_selected_cols = select(NYC_subway,colnames(NYC_subway)[2:18],vending,ada)%>%
  mutate(
    entry = entry=="YES" #Only yes/no in this column
  )%>%
  unique()

NYC_subway_selected_cols
```

    ## # A tibble: 684 × 19
    ##    line     station_…¹ stati…² stati…³ route1 route2 route3 route4 route5 route6
    ##    <chr>    <chr>        <dbl>   <dbl> <chr>  <chr>  <chr>  <chr>  <chr>  <chr> 
    ##  1 4 Avenue 25th St       40.7   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  2 4 Avenue 36th St       40.7   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  3 4 Avenue 45th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  4 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  5 4 Avenue 53rd St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  6 4 Avenue 59th St       40.6   -74.0 N      R      <NA>   <NA>   <NA>   <NA>  
    ##  7 4 Avenue 77th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  8 4 Avenue 77th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ##  9 4 Avenue 86th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## 10 4 Avenue 95th St       40.6   -74.0 R      <NA>   <NA>   <NA>   <NA>   <NA>  
    ## # … with 674 more rows, 9 more variables: route7 <chr>, route8 <dbl>,
    ## #   route9 <dbl>, route10 <dbl>, route11 <dbl>, entrance_type <chr>,
    ## #   entry <lgl>, vending <chr>, ada <lgl>, and abbreviated variable names
    ## #   ¹​station_name, ²​station_latitude, ³​station_longitude

``` r
colSums(is.na(NYC_subway_selected_cols))
```

    ##              line      station_name  station_latitude station_longitude 
    ##                 0                 0                 0                 0 
    ##            route1            route2            route3            route4 
    ##                 0               312               511               566 
    ##            route5            route6            route7            route8 
    ##               590               636               652               664 
    ##            route9           route10           route11     entrance_type 
    ##               673               677               677                 0 
    ##             entry           vending               ada 
    ##                 0                 0                 0

For the cleaning, I firstly clean the variable names and then extracted
the required columns with `select()` and convert the enry variable to
boolean value with `mutate()`. Then I removed duplicated rows. I checked
the missing value through `colSums()` and find that there is no missing
value except in routes information.

This dataset contains following variables line, station_name,
station_latitude, station_longitude, route1, route2, route3, route4,
route5, route6, route7, route8, route9, route10, route11, entrance_type,
entry, vending, ada after cleaning. And it is 684, 19(rows x columns).
Considering the previous statement, I think the data is tidy.

-   There are 465 distinct stations
-   84 stations are ADA compliant.
-   The proportion is 567:117 equals to 0.8289474

### Problem 2

#### load and clean the data

``` r
MrTrashWheel = read_xlsx('Datasets/Trash＿Wheel＿Collection.xlsx', 
                                  range ="Mr. Trash Wheel!A2:N535")%>%
  janitor::clean_names()

MrTrashWheel_cleaned = MrTrashWheel[is.na(MrTrashWheel$dumpster)==FALSE & MrTrashWheel$dumpster!='Grand Total',]%>%
  mutate(
    sports_balls = as.integer(sports_balls)
  )
#
ProfessorTrashWheel = read_xlsx('Datasets/Trash＿Wheel＿Collection.xlsx', 
                                  range ="Professor Trash Wheel!A2:N117")%>%
  janitor::clean_names()

ProfessorTrashWheel_cleaned = ProfessorTrashWheel[is.na(ProfessorTrashWheel$dumpster)==FALSE,]%>%
  mutate(
    sports_balls = as.integer(sports_balls)
  )

MrTrashWheel_cleaned
```

    ## # A tibble: 453 × 14
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##    <chr>    <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 443 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

``` r
ProfessorTrashWheel_cleaned
```

    ## # A tibble: 71 × 14
    ##    dumpster month     year date                weight_…¹ volum…² plast…³ polys…⁴
    ##       <dbl> <chr>    <dbl> <dttm>                  <dbl>   <dbl>   <dbl>   <dbl>
    ##  1        1 January   2017 2017-01-02 00:00:00      1.79      15    1950    6080
    ##  2        2 January   2017 2017-01-30 00:00:00      1.58      15    9540   11230
    ##  3        3 February  2017 2017-02-26 00:00:00      2.32      18    8350    9210
    ##  4        4 February  2017 2017-02-26 00:00:00      3.72      15    8590    1030
    ##  5        5 February  2017 2017-02-28 00:00:00      1.45      15    7830    9950
    ##  6        6 March     2017 2017-03-30 00:00:00      1.71      15    8210   10340
    ##  7        7 April     2017 2017-04-01 00:00:00      1.82      15    9830   11020
    ##  8        8 April     2017 2017-04-20 00:00:00      2.37      15    9240    8760
    ##  9        9 May       2017 2017-05-10 00:00:00      2.64      15    9540    8810
    ## 10       10 May       2017 2017-05-26 00:00:00      2.78      15    8230    7800
    ## # … with 61 more rows, 6 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, and abbreviated variable names
    ## #   ¹​weight_tons, ²​volume_cubic_yards, ³​plastic_bottles, ⁴​polystyrene

#### combine the two sets

``` r
MrTrashWheel_cleaned$whell_type = "MrTrash"
ProfessorTrashWheel_cleaned$whell_type = "ProfessorTrash"
ProfessorTrashWheel_cleaned$dumpster =as.character(ProfessorTrashWheel_cleaned$dumpster) 

cTrashWhell = bind_rows(MrTrashWheel_cleaned,ProfessorTrashWheel_cleaned)
cTrashWhell
```

    ## # A tibble: 524 × 15
    ##    dumpster month  year date                weight_tons volume…¹ plast…² polys…³
    ##    <chr>    <chr> <dbl> <dttm>                    <dbl>    <dbl>   <dbl>   <dbl>
    ##  1 1        May    2014 2014-05-16 00:00:00        4.31       18    1450    1820
    ##  2 2        May    2014 2014-05-16 00:00:00        2.74       13    1120    1030
    ##  3 3        May    2014 2014-05-16 00:00:00        3.45       15    2450    3100
    ##  4 4        May    2014 2014-05-17 00:00:00        3.1        15    2380    2730
    ##  5 5        May    2014 2014-05-17 00:00:00        4.06       18     980     870
    ##  6 6        May    2014 2014-05-20 00:00:00        2.71       13    1430    2140
    ##  7 7        May    2014 2014-05-21 00:00:00        1.91        8     910    1090
    ##  8 8        May    2014 2014-05-28 00:00:00        3.7        16    3580    4310
    ##  9 9        June   2014 2014-06-05 00:00:00        2.52       14    2400    2790
    ## 10 10       June   2014 2014-06-11 00:00:00        3.76       18    1340    1730
    ## # … with 514 more rows, 7 more variables: cigarette_butts <dbl>,
    ## #   glass_bottles <dbl>, grocery_bags <dbl>, chip_bags <dbl>,
    ## #   sports_balls <int>, homes_powered <dbl>, whell_type <chr>, and abbreviated
    ## #   variable names ¹​volume_cubic_yards, ²​plastic_bottles, ³​polystyrene

There are 524 observations with 15 variables in this combined dataset.

The key variables contains dumpster, time mark, trash types, whell type
etc. The total weight of trash collected by the professor trash wheel is
135.5 and total number of sports balls collected by Mr. Trash Wheel in
2020 is 856.
